const fs = require('fs');
let src = fs.readFileSync('src/components/QuestTab.jsx', 'utf8');
// Normalize trailing spaces on blank lines so matching is reliable
src = src.replace(/[ \t]+\n/g, '\n');

// ─── Outer card border + glow ─────────────────────────────────────────────────
src = src.replace(
  `              border: '2px solid rgba(0, 0, 0, 0.5)',\n              boxShadow: '0 4px 20px rgba(0, 0, 0, 0.5), inset 0 0 50px rgba(0, 0, 0, 0.3)'`,
  `              border: (() => { const m={red:'rgba(180,30,30,0.5)',blue:'rgba(59,130,246,0.4)',green:'rgba(30,80,140,0.4)',white:'rgba(200,200,200,0.35)',purple:'rgba(139,92,246,0.4)',yellow:'rgba(212,175,55,0.4)',amber:'rgba(34,197,94,0.4)'}; return '2px solid '+(m[hero.class.color]||m.yellow); })(),\n              boxShadow: (() => { const m={red:'rgba(180,30,30,0.25)',blue:'rgba(59,130,246,0.2)',green:'rgba(30,80,140,0.2)',white:'rgba(200,200,200,0.15)',purple:'rgba(139,92,246,0.2)',yellow:'rgba(212,175,55,0.2)',amber:'rgba(34,197,94,0.2)'}; const g=m[hero.class.color]||m.yellow; return '0 4px 30px '+g+', 0 0 60px '+g+', inset 0 0 50px rgba(0,0,0,0.4)'; })()`
);

// ─── Collapsed: watermark font size ──────────────────────────────────────────
src = src.replace(
  `style={{fontSize: '8rem', lineHeight: 1, opacity: 0.05, color: '#F5F5DC'}}>`,
  `style={{fontSize: '7rem', lineHeight: 1, opacity: 0.06, color: '#F5F5DC'}}>`
);

// ─── Collapsed: replace level badge with name+level header row ───────────────
src = src.replace(
  `                  {/* Level badge in top right corner */}\n                  <div className="absolute top-2 right-2 px-3 py-1 rounded-lg border-2" style={{\n                    background: 'rgba(0, 0, 0, 0.8)',\n                    borderColor: 'rgba(212, 175, 55, 0.6)',\n                    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.3)'\n                  }}>\n                    <span className="text-xs font-bold" style={{color: '#D4AF37', letterSpacing: '0.1em'}}>LVL {level}</span>\n                  </div>\n\n                  <div className="relative z-10 py-1">\n                    {/* Hero name - large and prominent in beige */}\n                    <div className="text-center mb-1">\n                      <h3 className="text-3xl font-black" style={{color: '#F5F5DC', letterSpacing: '0.08em'}}>{hero.name}</h3>\n                      <p className="text-sm mt-1" style={{color: COLORS.silver}}>{hero.class.name}</p>\n                    </div>`,
  `                  <div className="relative z-10">\n                    {/* Header: name left, level right */}\n                    <div className="flex items-center justify-between mb-2">\n                      <div>\n                        <h3 className="font-black uppercase" style={{fontFamily:'Cinzel,serif',fontSize:'clamp(1.4rem,4vw,1.9rem)',letterSpacing:'0.06em',color:'#F5F5DC',textShadow:(()=>{const m={red:'rgba(220,50,50,0.5)',blue:'rgba(96,165,250,0.5)',green:'rgba(59,130,246,0.5)',white:'rgba(220,220,220,0.4)',purple:'rgba(167,139,250,0.5)',yellow:'rgba(212,175,55,0.5)',amber:'rgba(34,197,94,0.5)'};return '0 0 20px '+(m[hero.class.color]||m.yellow);})()}}>{hero.name}</h3>\n                        <p className="text-xs uppercase tracking-widest mt-0.5" style={{color:'rgba(245,245,220,0.45)',fontFamily:'Cinzel,serif'}}>{hero.title} {hero.class.name}</p>\n                      </div>\n                      <div className="text-right">\n                        <div className="px-3 py-1 rounded border" style={{background:'rgba(0,0,0,0.5)',borderColor:'rgba(212,175,55,0.4)'}}>\n                          <span className="text-xs font-bold" style={{color:'#D4AF37',letterSpacing:'0.1em',fontFamily:'Cinzel,serif'}}>LVL {level}</span>\n                        </div>\n                        <p className="text-xs mt-1" style={{color:'rgba(245,245,220,0.4)'}}>Day {currentDay}</p>\n                      </div>\n                    </div>`
);

// ─── Collapsed: HP bar ────────────────────────────────────────────────────────
src = src.replace(
  `                    {/* HP and Stamina side-by-side */}\n                    <div className="grid grid-cols-2 gap-2 mb-3">\n                      {/* HP Bar */}\n                      <div className="rounded-lg p-2" style={{background: 'rgba(0, 0, 0, 0.3)', border: '1px solid rgba(139, 0, 0, 0.3)'}}>\n                        <div className="flex justify-between items-center mb-1">\n                          <span className="text-xs uppercase tracking-wide" style={{color: COLORS.silver}}>HP</span>\n                          <span className="text-xs font-bold" style={{color: hp <= 10 ? '#DC2626' : '#F5F5DC'}}>{hp}/{getMaxHp()}</span>\n                        </div>\n                        <div className="rounded-full h-1.5 overflow-hidden" style={{background: 'rgba(0, 0, 0, 0.5)'}}>\n                          <div\n                            className="h-1.5 rounded-full transition-all"\n                            style={{\n                              width: \`\${(hp / getMaxHp()) * 100}%\`,\n                              background: hp <= 10 ? 'linear-gradient(to right, #5A0E15, #8B1A28)' : 'linear-gradient(to right, #6B1318, #9B1B30)'\n                            }}\n                          />\n                        </div>\n                      </div>\n\n                      {/* Stamina Bar */}\n                      <div className="rounded-lg p-2" style={{background: 'rgba(0, 0, 0, 0.3)', border: '1px solid rgba(30, 58, 95, 0.3)'}}>\n                        <div className="flex justify-between items-center mb-1">\n                          <span className="text-xs uppercase tracking-wide" style={{color: COLORS.silver}}>SP</span>\n                          <span className="text-xs font-bold" style={{color: '#93C5FD'}}>{stamina}/{getMaxStamina()}</span>\n                        </div>\n                        <div className="rounded-full h-1.5 overflow-hidden" style={{background: 'rgba(0, 0, 0, 0.5)'}}>\n                          <div\n                            className="h-1.5 rounded-full transition-all"\n                            style={{\n                              width: \`\${(stamina / getMaxStamina()) * 100}%\`,\n                              background: 'linear-gradient(to right, #0C4A6E, #0EA5E9)'\n                            }}\n                          />\n                        </div>\n                      </div>\n                    </div>`,
  `                    {/* HP Bar */}\n                    <div className="mb-2">\n                      <div className="flex justify-between items-center mb-1">\n                        <span className="text-xs uppercase tracking-widest font-bold" style={{color:'#FF6B6B'}}>HP</span>\n                        <span className="text-xs font-bold" style={{color:hp/getMaxHp()<0.25?'#EF4444':'#F5F5DC'}}>{hp} / {getMaxHp()}</span>\n                      </div>\n                      <div className="rounded h-2.5 overflow-hidden" style={{background:'rgba(0,0,0,0.6)',border:'1px solid rgba(139,0,0,0.4)'}}>\n                        <div className="h-full rounded transition-all duration-300" style={{width:\`\${(hp/getMaxHp())*100}%\`,background:hp/getMaxHp()<0.25?'linear-gradient(to right,#7F1D1D,#DC2626)':'linear-gradient(to right,#7f1d1d,#b91c1c,#dc2626)'}}/>\n                      </div>\n                    </div>\n                    {/* SP Bar */}\n                    <div className="mb-3">\n                      <div className="flex justify-between items-center mb-1">\n                        <span className="text-xs uppercase tracking-widest font-bold" style={{color:'#60A5FA'}}>SP</span>\n                        <span className="text-xs font-bold" style={{color:'#93C5FD'}}>{stamina} / {getMaxStamina()}</span>\n                      </div>\n                      <div className="rounded h-2.5 overflow-hidden" style={{background:'rgba(0,0,0,0.6)',border:'1px solid rgba(30,58,140,0.4)'}}>\n                        <div className="h-full rounded transition-all duration-300" style={{width:\`\${(stamina/getMaxStamina())*100}%\`,background:'linear-gradient(to right,#1e3a8a,#2563eb,#3b82f6)'}}/>\n                      </div>\n                    </div>`
);

// ─── Collapsed: curse status ──────────────────────────────────────────────────
src = src.replace(
  `                    {/* Curse Status - Collapsed View */}\n                    {curseLevel > 0 && (\n                      <div\n                        className={\`rounded-lg p-2 mb-2 border \${curseLevel === 3 ? 'animate-pulse' : ''}\`}\n                        style={{\n                          backgroundColor: 'rgba(107, 44, 145, 0.3)',\n                          borderColor: curseLevel === 3 ? 'rgba(220, 38, 38, 0.6)' : 'rgba(138, 59, 181, 0.5)',\n                          boxShadow: curseLevel === 3 ? '0 0 15px rgba(220, 38, 38, 0.3)' : '0 0 10px rgba(138, 59, 181, 0.2)'\n                        }}\n                      >\n                        <div className="flex items-center justify-between">\n                          <div className="flex items-center gap-2">\n                            <span style={{fontSize: '1rem'}}>\n                              {curseLevel === 1 ? '🌑' : curseLevel === 2 ? '🌑🌑' : '☠️'}\n                            </span>\n                            <p className="text-xs font-bold uppercase" style={{color: curseLevel === 3 ? '#FF6B6B' : '#B794F4'}}>\n                              {curseLevel === 1 ? 'CURSED' : curseLevel === 2 ? 'DEEPLY CURSED' : 'CONDEMNED'}\n                            </p>\n                          </div>\n                          <p className="text-xs" style={{color: '#B794F4'}}>\n                            {curseLevel}/3\n                          </p>\n                        </div>\n                      </div>\n                    )}`,
  `                    {curseLevel > 0 && (\n                      <div className={\`rounded p-2 mb-3 \${curseLevel===3?'animate-pulse':''}\`} style={{background:'rgba(107,44,145,0.25)',border:\`1px solid \${curseLevel===3?'rgba(220,38,38,0.6)':'rgba(138,59,181,0.45)'}\`}}>\n                        <div className="flex items-center justify-between">\n                          <p className="text-xs font-bold uppercase" style={{color:curseLevel===3?'#FF6B6B':'#B794F4',fontFamily:'Cinzel,serif'}}>{curseLevel===1?'Cursed':curseLevel===2?'Deeply Cursed':'Condemned'}</p>\n                          <p className="text-xs" style={{color:'#B794F4'}}>{curseLevel}/3</p>\n                        </div>\n                      </div>\n                    )}`
);

// ─── Collapsed: expand button ─────────────────────────────────────────────────
src = src.replace(
  `                    {/* Expand Button - Centered */}\n                    <div className="flex justify-center">\n                      <button\n                        onClick={() => setHeroCardCollapsed(!heroCardCollapsed)}\n                        className="px-3 py-1 rounded transition-all border-2 hover:scale-105"\n                        style={{\n                          background: 'rgba(0, 0, 0, 0.5)',\n                          borderColor: 'rgba(212, 175, 55, 0.4)',\n                          color: '#D4AF37',\n                          fontSize: '0.7rem',\n                          letterSpacing: '0.1em'\n                        }}\n                      >\n                        \u25bc EXPAND HERO CARD\n                      </button>\n                    </div>`,
  `                    <button onClick={() => setHeroCardCollapsed(false)} className="w-full py-1.5 rounded text-xs uppercase tracking-widest transition-all hover:opacity-80" style={{background:'rgba(0,0,0,0.4)',border:'1px solid rgba(212,175,55,0.25)',color:'rgba(212,175,55,0.6)',fontFamily:'Cinzel,serif'}}>\n                      \u25bc Show Full Card\n                    </button>`
);

// ─── Expanded: watermark ──────────────────────────────────────────────────────
src = src.replace(
  `style={{fontSize: '20rem', lineHeight: 1, opacity: 0.05, color: '#F5F5DC'}}>`,
  `style={{fontSize: '20rem', lineHeight: 1, opacity: 0.04, color: '#F5F5DC'}}>`
);

// ─── Expanded: day/level badges ───────────────────────────────────────────────
src = src.replace(
  `              {/* Day badge in top left corner */}\n              <div className="absolute top-0 left-0 px-3 py-1 rounded-br-lg border-2 z-20" style={{\n                background: 'rgba(0, 0, 0, 0.5)',\n                borderColor: 'rgba(212, 175, 55, 0.4)',\n                borderTop: 'none',\n                borderLeft: 'none'\n              }}>\n                <span className="text-xs font-bold" style={{color: '#D4AF37', letterSpacing: '0.1em'}}>DAY {currentDay}</span>\n              </div>\n\n              {/* Level badge in top right corner */}\n              <div className="absolute top-0 right-0 px-3 py-1 rounded-bl-lg border-2 z-20" style={{\n                background: 'rgba(0, 0, 0, 0.5)',\n                borderColor: 'rgba(212, 175, 55, 0.4)',\n                borderTop: 'none',\n                borderRight: 'none'\n              }}>\n                <span className="text-xs font-bold" style={{color: '#D4AF37', letterSpacing: '0.1em'}}>LVL {level}</span>\n              </div>`,
  `              {/* Corner badges */}\n              <div className="absolute top-0 left-0 px-3 py-1 rounded-br-lg z-20" style={{background:'rgba(0,0,0,0.6)',border:'1px solid rgba(212,175,55,0.3)',borderTop:'none',borderLeft:'none'}}>\n                <span className="text-xs font-bold" style={{color:'rgba(212,175,55,0.7)',letterSpacing:'0.1em',fontFamily:'Cinzel,serif'}}>DAY {currentDay}</span>\n              </div>\n              <div className="absolute top-0 right-0 px-3 py-1 rounded-bl-lg z-20" style={{background:'rgba(0,0,0,0.6)',border:'1px solid rgba(212,175,55,0.3)',borderTop:'none',borderRight:'none'}}>\n                <span className="text-xs font-bold" style={{color:'rgba(212,175,55,0.7)',letterSpacing:'0.1em',fontFamily:'Cinzel,serif'}}>LVL {level}</span>\n              </div>`
);

// ─── Expanded: hero name block ────────────────────────────────────────────────
src = src.replace(
  `                {/* Hero name and title */}\n                <div className="text-center mb-3 pt-6">\n                  <h2 className="text-4xl font-bold mb-1 uppercase" style={{color: '#F5F5DC', letterSpacing: '0.1em'}}>{hero.name}</h2>\n                  <p className="text-sm uppercase tracking-wide" style={{color: '#F5F5DC'}}>{hero.title} {hero.class.name}</p>\n                  <div className="flex items-center justify-center gap-2 mt-2">\n                    <div style={{width: '40px', height: '1px', background: 'rgba(245, 245, 220, 0.3)'}}></div>\n                    <span style={{color: 'rgba(245, 245, 220, 0.5)', fontSize: '8px'}}>◆</span>\n                    <div style={{width: '40px', height: '1px', background: 'rgba(245, 245, 220, 0.3)'}}></div>\n                  </div>\n                </div>`,
  `                {/* Hero name — cinematic */}\n                <div className="text-center mb-4 pt-7">\n                  <h2 className="font-black uppercase" style={{fontFamily:'Cinzel,serif',fontSize:'clamp(2rem,5vw,3.2rem)',letterSpacing:'0.1em',lineHeight:1.1,color:'#F5F5DC',textShadow:(()=>{const m={red:'rgba(220,50,50,0.7)',blue:'rgba(96,165,250,0.7)',green:'rgba(59,130,246,0.7)',white:'rgba(220,220,220,0.6)',purple:'rgba(167,139,250,0.7)',yellow:'rgba(212,175,55,0.7)',amber:'rgba(34,197,94,0.7)'};const c=m[hero.class.color]||m.yellow;return \`0 0 30px \${c}, 0 0 60px \${c.replace('0.7','0.3')}, 0 2px 0 rgba(0,0,0,0.9)\`;})()}}>{hero.name}</h2>\n                  <p className="text-xs uppercase tracking-[0.35em] mt-1.5" style={{color:'rgba(245,245,220,0.45)',fontFamily:'Cinzel,serif'}}>{hero.title} {hero.class.name}</p>\n                  <div className="flex items-center justify-center gap-2 mt-2">\n                    {(()=>{const m={red:'rgba(220,50,50,0.5)',blue:'rgba(96,165,250,0.5)',green:'rgba(59,130,246,0.5)',white:'rgba(200,200,200,0.4)',purple:'rgba(167,139,250,0.5)',yellow:'rgba(212,175,55,0.5)',amber:'rgba(34,197,94,0.5)'};const c=m[hero.class.color]||m.yellow;return(<><div style={{width:'60px',height:'1px',background:\`linear-gradient(to right,transparent,\${c})\`}}></div><span style={{color:c,fontSize:'8px'}}>◆</span><div style={{width:'60px',height:'1px',background:\`linear-gradient(to left,transparent,\${c})\`}}></div></>);})()}\n                  </div>\n                </div>`
);

// ─── Expanded: HP stat box ────────────────────────────────────────────────────
src = src.replace(
  `                  {/* HP */}\n                  <div className="rounded-lg p-2 text-center" style={{\n                    backgroundColor: 'rgba(0, 0, 0, 0.35)',\n                    border: '2px solid rgba(0, 0, 0, 0.3)',\n                    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.05)'\n                  }}>\n                    <div className="flex justify-center mb-1">\n                      <HeartPulse size={20} style={{color: '#FF6B6B'}}/>\n                    </div>\n                    <p className="text-xl font-bold mb-1" style={{color: '#F5F5DC'}}>{hp}/{getMaxHp()}</p>\n                    <div className="rounded-full h-2 overflow-hidden" style={{backgroundColor: 'rgba(0, 0, 0, 0.5)'}}>\n                      <div className="h-2 rounded-full transition-all duration-300" style={{backgroundColor: '#DC2626', width: \`\${(hp / getMaxHp()) * 100}%\`}}></div>\n                    </div>\n                  </div>`,
  `                  {/* HP */}\n                  <div className="rounded-lg p-3" style={{background:'rgba(0,0,0,0.4)',border:'1px solid rgba(139,0,0,0.5)',boxShadow:'inset 0 2px 6px rgba(0,0,0,0.4)'}}>\n                    <div className="flex justify-between items-center mb-1.5"><div className="flex items-center gap-1.5"><HeartPulse size={14} style={{color:'#FF6B6B'}}/><span className="text-xs font-bold uppercase tracking-widest" style={{color:'#FF6B6B'}}>HP</span></div><span className="text-sm font-bold" style={{color:hp/getMaxHp()<0.25?'#EF4444':'#F5F5DC'}}>{hp}/{getMaxHp()}</span></div>\n                    <div className="rounded h-3 overflow-hidden" style={{background:'rgba(0,0,0,0.6)',border:'1px solid rgba(139,0,0,0.3)'}}><div className="h-full rounded transition-all duration-300" style={{width:\`\${(hp/getMaxHp())*100}%\`,background:hp/getMaxHp()<0.25?'linear-gradient(to right,#7F1D1D,#DC2626)':'linear-gradient(to right,#7f1d1d,#b91c1c,#ef4444)'}}/></div>\n                  </div>`
);

// ─── Expanded: Stamina stat box ───────────────────────────────────────────────
src = src.replace(
  `                  {/* Stamina */}\n                  <div className="rounded-lg p-2 text-center" style={{\n                    backgroundColor: 'rgba(0, 0, 0, 0.35)',\n                    border: '2px solid rgba(0, 0, 0, 0.3)',\n                    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.05)'\n                  }}>\n                    <div className="flex justify-center mb-1">\n                      <Sparkles size={20} style={{color: '#3B82F6'}}/>\n                    </div>\n                    <p className="text-xl font-bold mb-1" style={{color: '#F5F5DC'}}>{stamina}/{getMaxStamina()}</p>\n                    <div className="rounded-full h-2 overflow-hidden" style={{backgroundColor: 'rgba(0, 0, 0, 0.5)'}}>\n                      <div className="h-2 rounded-full transition-all duration-300" style={{backgroundColor: '#3B82F6', width: \`\${(stamina / getMaxStamina()) * 100}%\`}}></div>\n                    </div>\n                  </div>`,
  `                  {/* Stamina */}\n                  <div className="rounded-lg p-3" style={{background:'rgba(0,0,0,0.4)',border:'1px solid rgba(30,58,140,0.5)',boxShadow:'inset 0 2px 6px rgba(0,0,0,0.4)'}}>\n                    <div className="flex justify-between items-center mb-1.5"><div className="flex items-center gap-1.5"><Sparkles size={14} style={{color:'#60A5FA'}}/><span className="text-xs font-bold uppercase tracking-widest" style={{color:'#60A5FA'}}>SP</span></div><span className="text-sm font-bold" style={{color:'#93C5FD'}}>{stamina}/{getMaxStamina()}</span></div>\n                    <div className="rounded h-3 overflow-hidden" style={{background:'rgba(0,0,0,0.6)',border:'1px solid rgba(30,58,140,0.3)'}}><div className="h-full rounded transition-all duration-300" style={{width:\`\${(stamina/getMaxStamina())*100}%\`,background:'linear-gradient(to right,#1e3a8a,#2563eb,#3b82f6)'}}/></div>\n                  </div>`
);

// ─── Expanded: Attack stat box ────────────────────────────────────────────────
src = src.replace(
  `                  {/* Attack */}\n                  <div className="rounded-lg p-2 text-center" style={{\n                    backgroundColor: 'rgba(0, 0, 0, 0.35)',\n                    border: '2px solid rgba(0, 0, 0, 0.3)',\n                    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.05)'\n                  }}>\n                    <div className="flex justify-center mb-1">\n                      <Swords size={20} style={{color: '#F59E0B'}}/>\n                    </div>\n                    <p className="text-xl font-bold mb-1" style={{color: '#F5F5DC'}}>{getBaseAttack()}</p>\n                    <p className="text-xs uppercase" style={{color: '#F5F5DC'}}>Damage Per Hit</p>\n                  </div>`,
  `                  {/* Attack */}\n                  <div className="rounded-lg p-3 text-center" style={{background:'rgba(0,0,0,0.4)',border:'1px solid rgba(180,100,0,0.4)',boxShadow:'inset 0 2px 6px rgba(0,0,0,0.4)'}}>\n                    <Swords size={18} style={{color:'#F59E0B',margin:'0 auto 6px'}}/>\n                    <p className="text-2xl font-black" style={{color:'#F5F5DC',fontFamily:'Cinzel,serif',lineHeight:1}}>{getBaseAttack()}</p>\n                    <p className="text-xs uppercase tracking-widest mt-1" style={{color:'rgba(245,245,220,0.45)'}}>Attack</p>\n                  </div>`
);

// ─── Expanded: Defense stat box ───────────────────────────────────────────────
src = src.replace(
  `                  {/* Defense */}\n                  <div className="rounded-lg p-2 text-center" style={{\n                    backgroundColor: 'rgba(0, 0, 0, 0.35)',\n                    border: '2px solid rgba(0, 0, 0, 0.3)',\n                    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.05)'\n                  }}>\n                    <div className="flex justify-center mb-1">\n                      <ShieldCheck size={20} style={{color: '#F5F5DC'}}/>\n                    </div>\n                    <p className="text-2xl font-bold mb-1" style={{color: '#F5F5DC'}}>{Math.floor((getBaseDefense() / (getBaseDefense() + 50)) * 100)}%</p>\n                    <p className="text-xs uppercase" style={{color: '#F5F5DC'}}>Damage Resist</p>\n                  </div>`,
  `                  {/* Defense */}\n                  <div className="rounded-lg p-3 text-center" style={{background:'rgba(0,0,0,0.4)',border:'1px solid rgba(100,120,160,0.4)',boxShadow:'inset 0 2px 6px rgba(0,0,0,0.4)'}}>\n                    <ShieldCheck size={18} style={{color:'#94A3B8',margin:'0 auto 6px'}}/>\n                    <p className="text-2xl font-black" style={{color:'#F5F5DC',fontFamily:'Cinzel,serif',lineHeight:1}}>{Math.floor((getBaseDefense() / (getBaseDefense() + 50)) * 100)}%</p>\n                    <p className="text-xs uppercase tracking-widest mt-1" style={{color:'rgba(245,245,220,0.45)'}}>Defense</p>\n                  </div>`
);

// ─── Expanded: collapse button text ──────────────────────────────────────────
src = src.replace(
  `                    {heroCardCollapsed ? '\u25bc EXPAND HERO CARD' : '\u25b2 COLLAPSE HERO CARD'}`,
  `                    \u25b2 Collapse`
);

fs.writeFileSync('src/components/QuestTab.jsx', src);
console.log('Done');
